spring.application.name=torneo-esports

spring.datasource.url=jdbc:mysql://mysql-torneo-esports-cibertec2.mysql.database.azure.com:3306/db_torneos_esports?useSSL=true&requireSSL=false&serverTimezone=UTC
spring.datasource.username=adminmysql
spring.datasource.password=Elkhearts03

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=8080  